# Template: PRD to CLAUDE.md
# Copia questo file in: .github/workflows/claude-prd.yml del tuo repo
#
# Prerequisiti:
# - Secret ANTHROPIC_API_KEY configurato nel repo (Settings > Secrets > Actions)
# - Cartella .claude/prds/ con almeno un file .md
#
# Trigger:
# - Automatico: quando vengono pushati file in .claude/prds/
# - Manuale: dalla tab Actions > Claude PRD Analysis > Run workflow

name: Claude PRD Analysis

on:
  push:
    paths:
      - '.claude/prds/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-claude-md:
    uses: Polloinfilzato/claude-workflows/.github/workflows/prd-to-claude-md.yml@main
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
